# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftWibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftWibo

  target 'SwiftWiboTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftWiboUITests' do
    inherit! :search_paths
    # Pods for testing
  end
#pod 'Masonry'
pod 'SnapKit'
pod 'AFNetworking'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'YYModel'
pod 'pop'
pod 'YYText'
end
